### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by PedroMMagalhaes** [yrambler2001/Hackintosh-Intel-i5-10600-iGPU-AsRock-B460M-Pro4#2]
Hi,
Did you try to install Big Sur on this system?

Thanks in advance

**Comment by yrambler2001** [comment]
Hi
No, I did not. I think Big Sur is not stable enough now and there will be improvements from kext developers.

**Comment by ahadrox** [comment]
Does this B460 chipset has native NVRAM support or it’s an emulated NVRAM?

**Comment by PedroMMagalhaes** [comment]
Thanks 👍
