### ISSUE TITLE
ASRock B460M/ac-itx    Do you support it?

### ISSUE THREAD

**Issue by Gollum916** [yrambler2001/Hackintosh-Intel-i5-10600-iGPU-AsRock-B460M-Pro4#4]
ASRock B460M/ac-itx    Do you support it?

**Comment by yrambler2001** [comment]
Hi @Gollum916, I think this efi will work fine, the differences I saw between my motherboard and your motherboard are:

1. Different audio codec: Realtek ALC887, so maybe you will need to change alcid in config.plist
2. You have Intel WiFi/BT card, I don't know if there is working kext for Intel WiFi support, also I don't have experience with Intel BT. I use external Bluetooh usb card which is compatible.

**Comment by Gollum916** [comment]
> @ Gollum916，您好：我认为此efi可以正常工作，我在母板和母板之间看到的差异是：
> 
> 1. 不同的音频编解码器：Realtek ALC887，所以也许您需要在config.plist中更改alcid
> 2. 您有Intel WiFi / BT卡，我不知道是否有适用于Intel WiFi支持的kext，也没有使用Intel BT的经验。我使用兼容的外部Bluetooh USB卡。

Thank you for your answer
