### ISSUE TITLE
about Big sur

### ISSUE THREAD

**Issue by zhangmx1995** [yrambler2001/Hackintosh-Intel-i5-10600-iGPU-AsRock-B460M-Pro4#6]
will it work on Big sur?

**Comment by yrambler2001** [comment]
Hi @zhangmx1995 
I will prepare it to Big Sur after Big Sur release + 1 month

**Comment by zhangmx1995** [comment]
OK,Thanks a lot

**Comment by matisiekpl** [comment]
@yrambler2001 Hello.
May I ask you what is not working on Big Sur? By first look, nothing is related to catalina, everything should work great on Big Sur.
If you tell whats not working, I think I can open PR with updates that support Big Sur

**Comment by yrambler2001** [comment]
Hi @matisiekpl. 
Thanks for your interest in this repo.
I have not tried Big Sur yet. Is Big Sur stable enough to install it as the main OS for everyday node.js development? Recently, I had installed an RX560 to be able to connect the third monitor, so I won't be able to test whether the iGPU is working well or not. Also, I found the colors, especially blue are, you know, like, have a deeper blue color on RX560. It is darker a bit.

**Comment by matisiekpl** [comment]
About stability: I used Big Sur betas 7-9 for everyday programming (dotnet, golang, cpp, dart) and remote lessons in school via Teams and Zoom. Everything was working great. No crashes, no drivers failures. I think that final release of Big Sur is working much better than betas, so it is extremely stable. 
About graphics: I have noticed, that when you connect dispay with hdmi and vga, colors are a bit diffrent. Tomorrow I'll try with DP-HDMI cable. It occurs also on Windows 10. 
About OC: so you think everything should work out of the box? I will try it tomorrow and give some feedback

**Comment by yrambler2001** [comment]
How could you test if it is working or not, do you have a similar PC?
Currently I don't know what should I change to prepare it to Big Sur, I planned to look into it right before I will install Big Sur.
So Big Sur is stable enough, I may install it to my pc on this weekend. What do you think, it is better to update from 'catalina update window' or make a clean install?)
Thanks.

**Comment by zhangmx1995** [comment]
> About stability: I used Big Sur betas 7-9 for everyday programming (dotnet, golang, cpp, dart) and remote lessons in school via Teams and Zoom. Everything was working great. No crashes, no drivers failures. I think that final release of Big Sur is working much better than betas, so it is extremely stable.
> About graphics: I have noticed, that when you connect dispay with hdmi and vga, colors are a bit diffrent. Tomorrow I'll try with DP-HDMI cable. It occurs also on Windows 10.
> About OC: so you think everything should work out of the box? I will try it tomorrow and give some feedback

I think it may be a possible choice for you to try my repository if you have a asrock-b460m mainboard device,I have test several betas of Big Sur with a opencore version 0.6.2 and all the hardware works.I have a d-gpu(rx590)on it.
If you use the i-gpu,I can help you to change the EFI files when I have spare time.The only thing you have to do is find out your lay-out ID for your audio.

**Comment by matisiekpl** [comment]
@yrambler2001 I have the sam setup as you (asrock B460m Pro4, i5 10400). Today I will test your efi with big sur

**Comment by matisiekpl** [comment]
@zhangmx1995 Keep in mind, that you need to update OC to 0.6.3, because Big Sur beta 10 and later increased kernel cache size. 
I will try EFI in this repo (OC upgraded to latest version) with NVMe SSD. If everything is ok, I will submit Pull Request with changes.

**Comment by matisiekpl** [comment]
Great news!
After some errors I finally ran macOS Big Sur on i5-10400 and ASRock B460M Pro4. Wishing few days I will open PR with upgraded OC to 0.6.3 and some important notes about installation. Currently I'm testing stability, everything looks great.
![image](https://user-images.githubusercontent.com/21008961/99547770-37b0ff80-29b8-11eb-95d1-a29b880b8351.png)
