### ISSUE TITLE
HDMI Problem：Purple screen On BigSur

### ISSUE THREAD

**Issue by IITII** [yrambler2001/Hackintosh-Intel-i5-10600-iGPU-AsRock-B460M-Pro4#8]
Hi, I'am using i5 10600K with  this efi. I'm using DP(OnBoard) when I install  BigSur. Every goes well.

> Only iGPU, Device id: 0x9BC5  

Then I try to using HDMI(OnBoard) for video output, then got a problem. 

> I want to using HDMI for DELL 2421D, DP for Apple LED Cinema(With mini DP to DP switcher)

A Purple screen and the resolution is also wrong.

I checked HackinTool and I  got this.

>  HDMI(Onboard): 0x05   
> DP(Onboard): 0x04  

It seems like a display port mapping  error , can  you help me?

![image](https://user-images.githubusercontent.com/33705067/132472469-52a5ff75-27ae-4bde-b52b-87681139bec2.png)

**Comment by IITII** [comment]
HDMI and DP output works well after remove some configure in `PciRoot(0x0)/Pci(0x2,0x0)`.
But I don't know what dose they means and make some side affect, any one can help me?

![image](https://user-images.githubusercontent.com/33705067/132704202-f834fae6-bb2b-4e80-a6d7-3337f9ccd0ea.png)

* All video ports are DP type when I check the hackintool after reboot my computer.

![image](https://user-images.githubusercontent.com/33705067/132704630-79594e08-a854-4a64-8a2f-f2e69e80188c.png)

**Comment by ameerzaheer** [comment]
I need you contact, have to talk about dell 5577 big sur, please reply

**Comment by IITII** [comment]
I think I found the why of abnormal resolution when using onboard HDMI port for OUTPUT.

It is cause by `framebuffer-patch`, remove or set its data to disable will fix it.

![image](https://user-images.githubusercontent.com/33705067/132789091-b7327fae-fbaf-4160-b055-f1d99b5a3a23.png)

![image](https://user-images.githubusercontent.com/33705067/132789293-7522043c-34ce-47f8-aee7-32cfab408dcd.png)
